inputSet:
  name: Build_golang_application_1689615193613-push-trigger-input-set
  identifier: Build_golang_application_1689615193613pushtriggerinputset
  orgIdentifier: default
  projectIdentifier: gosample
  pipeline:
    identifier: Build_golang_application_1689615193613
    properties:
      ci:
        codebase:
          build:
            type: branch
            spec:
              branch: <+trigger.branch>
